# Generated by Django 3.1.3 on 2021-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reivew',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
