# Generated by Django 3.1.3 on 2021-05-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igo', '0002_auto_20210511_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reivew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
