# Generated by Django 3.1.3 on 2021-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igo', '0004_auto_20210511_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
