# Generated by Django 3.1.3 on 2021-05-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igo', '0005_auto_20210513_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
