# Generated by Django 3.1.3 on 2021-05-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igo', '0006_auto_20210513_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
