# Generated by Django 3.1.3 on 2021-05-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igo', '0008_auto_20210513_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='imagee',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
