# Generated by Django 3.1.3 on 2021-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igo', '0009_review_imagee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='imagee',
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
