# Generated by Django 3.1.3 on 2021-05-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igo', '0013_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
