# Generated by Django 3.1.3 on 2021-05-30 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('igo', '0020_comment1_comment2_comment3_comment4_comment5'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='voter',
            field=models.ManyToManyField(related_name='voter_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review1',
            name='voter',
            field=models.ManyToManyField(related_name='voter_question1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review2',
            name='voter',
            field=models.ManyToManyField(related_name='voter_question2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review3',
            name='voter',
            field=models.ManyToManyField(related_name='voter_question3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review4',
            name='voter',
            field=models.ManyToManyField(related_name='voter_question4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review5',
            name='voter',
            field=models.ManyToManyField(related_name='voter_question5', to=settings.AUTH_USER_MODEL),
        ),
    ]
