# Generated by Django 3.1.3 on 2021-05-30 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('igo', '0021_auto_20210531_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='voter',
            field=models.ManyToManyField(related_name='voter_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review1',
            name='voter',
            field=models.ManyToManyField(related_name='voter_review1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review2',
            name='voter',
            field=models.ManyToManyField(related_name='voter_review2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review3',
            name='voter',
            field=models.ManyToManyField(related_name='voter_review3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review4',
            name='voter',
            field=models.ManyToManyField(related_name='voter_review4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review5',
            name='voter',
            field=models.ManyToManyField(related_name='voter_review5', to=settings.AUTH_USER_MODEL),
        ),
    ]
