# Generated by Django 3.1.3 on 2021-05-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igo', '0025_auto_20210601_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment1',
            old_name='review',
            new_name='review1',
        ),
    ]
