# Generated by Django 3.1.3 on 2021-05-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igo', '0026_auto_20210601_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment1',
            old_name='review1',
            new_name='review',
        ),
    ]
