from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from .views import base_views,comment_views,list_views,review_views,vote_views



app_name = 'igo'

urlpatterns = [
    path('', base_views.realindex, name='realindex'),
    path(r'igo/review_list', base_views.index, name='index'),
    path(r'igo/review_list_snack_bar', base_views.index1, name='index1'),
    path(r'igo/review_list_korea_food', base_views.index2, name='index2'),
    path(r'igo/review_list_japan', base_views.index3, name='index3'),
    path(r'igo/review_list_china', base_views.index4, name='index4'),
    path(r'igo/review_list_cafe', base_views.index5, name='index5'),
    path(r'igo/notion_list', base_views.index7, name='index7'),
    path(r'igo/family_list_detail', base_views.index_best, name='index_best'),
    path('review/detail/<int:review_id>/', base_views.detail, name='detail'),
    path('review1/detail1/<int:review_id1>/', base_views.detail1, name='detail1'),
    path('review2/detail2/<int:review_id2>/', base_views.detail2, name='detail2'),
    path('review3/detail3/<int:review_id3>/', base_views.detail3, name='detail3'),
    path('review4/detail4/<int:review_id4>/', base_views.detail4, name='detail4'),
    path('review5/detail5/<int:review_id5>/', base_views.detail5, name='detail5'),
    path('review7/detail7/<int:review_id7>/', base_views.detail7, name='detail7'),
    path('review/detail/best/<int:review_id6>/', base_views.detail_best, name='detail_best'),
    path('review/create/', review_views.review_create, name='review_create'),
    path('review1/create1/', review_views.review_create1, name='review_create1'),
    path('review2/create2/', review_views.review_create2, name='review_create2'),
    path('review3/create3/', review_views.review_create3, name='review_create3'),
    path('review4/create4/', review_views.review_create4, name='review_create4'),
    path('review5/create5/', review_views.review_create5, name='review_create5'),
    path('review7/create7/', review_views.review_create7, name='review_create7'),
    path('review/create/best', review_views.review_create_best, name='review_create_best'),
    path('review/modify/<int:review_id>/', review_views.review_modify, name='review_modify'),
    path('review1/modify1/<int:review_id1>/', review_views.review_modify1, name='review_modify1'),
    path('review2/modify2/<int:review_id2>/', review_views.review_modify2, name='review_modify2'),
    path('review3/modify3/<int:review_id3>/', review_views.review_modify3, name='review_modify3'),
    path('review4/modify4/<int:review_id4>/', review_views.review_modify4, name='review_modify4'),
    path('review5/modify5/<int:review_id5>/', review_views.review_modify5, name='review_modify5'),
    path('review7/modify7/<int:review_id7>/', review_views.review_modify7, name='review_modify7'),
    path('review/delete/<int:review_id>/', review_views.review_delete, name='review_delete'),
    path('review1/delete1/<int:review_id1>/', review_views.review_delete1, name='review_delete1'),
    path('review2/delete2/<int:review_id2>/', review_views.review_delete2, name='review_delete2'),
    path('review3/delete3/<int:review_id3>/', review_views.review_delete3, name='review_delete3'),
    path('review4/delete4/<int:review_id4>/', review_views.review_delete4, name='review_delete4'),
    path('review5/delete5/<int:review_id5>/', review_views.review_delete5, name='review_delete5'),
    path('review7/delete7/<int:review_id7>/', review_views.review_delete7, name='review_delete7'),
    path(r'igo/family_list', list_views.list, name='list'),
    path(r'igo/friend_list', list_views.list1, name='list1'),
    path(r'igo/cj_list', list_views.list2, name='list2'),
    path(r'igo/famous_list', list_views.list3, name='list3'),
    path(r'igo/igo/family_list_detail', list_views.list_detail, name='list_detail'),
    path(r'igo/igo/friend_list_detail', list_views.list_detail1, name='list_detail1'),
    path(r'igo/igo/cj_list_detail', list_views.list_detail2, name='list_detail2'),
    path(r'igo/igo/famous_list_detail', list_views.list_detail3, name='list_detail3'),
    path('comment/create/review/<int:review_id>/', comment_views.comment_create_review, name='comment_create_review'),
    path('comment1/create1/review1/<int:review_id1>/', comment_views.comment_create_review1, name='comment_create_review1'),
    path('comment2/create2/review2/<int:review_id2>/', comment_views.comment_create_review2, name='comment_create_review2'),
    path('comment3/create3/review3/<int:review_id3>/', comment_views.comment_create_review3, name='comment_create_review3'),
    path('comment4/create4/review4/<int:review_id4>/', comment_views.comment_create_review4, name='comment_create_review4'),
    path('comment5/create5/review5/<int:review_id5>/', comment_views.comment_create_review5, name='comment_create_review5'),
    path('comment7/create7/review7/<int:review_id7>/', comment_views.comment_create_review7, name='comment_create_review7'),
    path('comment/modify/review/<int:comment_id>/', comment_views.comment_modify_review, name='comment_modify_review'),
    path('comment1/modify1/review1/<int:comment_id1>/', comment_views.comment_modify_review1, name='comment_modify_review1'),
    path('comment2/modify2/review2/<int:comment_id2>/', comment_views.comment_modify_review2, name='comment_modify_review2'),
    path('comment3/modify3/review3/<int:comment_id3>/', comment_views.comment_modify_review3, name='comment_modify_review3'),
    path('comment4/modify4/review4/<int:comment_id4>/', comment_views.comment_modify_review4, name='comment_modify_review4'),
    path('comment5/modify5/review5/<int:comment_id5>/', comment_views.comment_modify_review5, name='comment_modify_review5'),
    path('comment7/modify7/review7/<int:comment_id7>/', comment_views.comment_modify_review7, name='comment_modify_review7'),
    path('comment/delete/<int:comment_id>/', comment_views.comment_delete_review, name='comment_delete_review'),
    path('comment1/delete1/<int:comment_id1>/', comment_views.comment_delete_review1, name='comment_delete_review1'),
    path('comment2/delete2/<int:comment_id2>/', comment_views.comment_delete_review2, name='comment_delete_review2'),
    path('comment3/delete3/<int:comment_id3>/', comment_views.comment_delete_review3, name='comment_delete_review3'),
    path('comment4/delete4/<int:comment_id4>/', comment_views.comment_delete_review4, name='comment_delete_review4'),
    path('comment5/delete5/<int:comment_id5>/', comment_views.comment_delete_review5, name='comment_delete_review5'),
    path('comment7/delete7/<int:comment_id7>/', comment_views.comment_delete_review7, name='comment_delete_review7'),
    path('vote/review/<int:review_id>/', vote_views.vote_review, name='vote_review'),
    path('vote/review1/<int:review_id1>/', vote_views.vote_review1, name='vote_review1'),
    path('vote/review2/<int:review_id2>/', vote_views.vote_review2, name='vote_review2'),
    path('vote/review3/<int:review_id3>/', vote_views.vote_review3, name='vote_review3'),
    path('vote/review4/<int:review_id4>/', vote_views.vote_review4, name='vote_review4'),
    path('vote/review5/<int:review_id5>/', vote_views.vote_review5, name='vote_review5'),
    path('vote/review7/<int:review_id7>/', vote_views.vote_review7, name='vote_review7'),
    ]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)